services:
  - type: web
    name: fleetinsight-fastapi
    env: python
    plan: free  # bisa kamu ubah ke starter untuk runtime lebih cepat
    region: singapore  # pilih region terdekat dengan Snowflake (APAC)
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn -w 2 -k uvicorn.workers.UvicornWorker main:app --timeout 120
    envVars:
      - key: SNOWFLAKE_ACCOUNT
        sync: false
      - key: SNOWFLAKE_USER
        sync: false
      - key: SNOWFLAKE_PASSWORD
        sync: false
      - key: SNOWFLAKE_WAREHOUSE
        sync: false
      - key: SNOWFLAKE_DATABASE
        sync: false
      - key: SNOWFLAKE_SCHEMA
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
